package com.github.squi2rel.mcng.core;

public enum GraphErrorCode {
	UNKNOWN_NODE_TYPE,
	DUPLICATE_NODE_ID,
	UNKNOWN_NODE,
	UNKNOWN_PORT,
	INVALID_EDGE_DIRECTION,
	CHANNEL_MISMATCH,
	TYPE_MISMATCH,
	CYCLE_DETECTED,
	CONTROL_CYCLE_DETECTED,
	MISSING_REQUIRED_INPUT,
	CONVERSION_FAILED,
	INVALID_INLINE_INPUT,
	INVALID_EVENT_SOURCE,
	UNKNOWN_VARIABLE,
	UNKNOWN_PORT_TYPE,
	INVALID_VARIABLE_VALUE,
	INVALID_CONTROL_BOUNDARY,
	MISSING_WHILE_BODY,
	CONTROL_STEP_LIMIT_EXCEEDED,
	WHILE_ITERATION_LIMIT_EXCEEDED,
	INVALID_DOCUMENT_DEFINITION,
	VALUE_LIMIT_EXCEEDED,
	NODE_EXECUTION_FAILED
}
